### ISSUE TITLE
Fails to download couchbase server when `{{ ansible_distribution_version }} == 16.04`

### ISSUE THREAD

**Issue by DanHartman** [mrlesmithjr/ansible-couchbase#2]
Attempted to run playbook against Ubuntu 16.04 instance.
This combination produces a url that doesn't exist.

[http://packages.couchbase.com/releases/4.5.0/couchbase-server-community_4.5.0-ubuntu16.04_amd64.deb](http://packages.couchbase.com/releases/4.5.0/couchbase-server-community_4.5.0-ubuntu16.04_amd64.deb)

It appears that 14.04 is the latest version in this url format.
![screen shot 2017-03-31 at 9 08 09 am](https://cloud.githubusercontent.com/assets/1824639/24553971/a358369c-15f1-11e7-8845-9ad29990aec5.png)

Perhaps we could leverage the [APT repository method](https://developer.couchbase.com/server/other-products/release-notes-archives/c-sdk).
![screen shot 2017-03-31 at 9 13 34 am](https://cloud.githubusercontent.com/assets/1824639/24554203/59d6f264-15f2-11e7-84a9-43cd1505dd15.png)

**Comment by mrlesmithjr** [comment]
@DanHartman Thanks for this. It appears that they still do not support Ubuntu 16.04. I will continue to do some checking.

**Comment by DanHartman** [comment]
This seems to work:
```yaml
- name: add couchbase key
  apt_key: 
    url: http://packages.couchbase.com/ubuntu/couchbase.key
    state: present

- name: add couchbase repo
  apt_repository:
    repo: 'deb http://packages.couchbase.com/ubuntu {{ ansible_distribution_release }} {{ ansible_distribution_release }} main' 
    update_cache: yes

- name: install couchbase
  apt: 
    update_cache: yes
    name: couchdb
```
